import axios from 'axios';
const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
const api = axios.create({ baseURL: API_URL });
api.interceptors.request.use(config => { if(typeof window!=='undefined'){const t=localStorage.getItem('token');if(t)config.headers.Authorization='Bearer '+t;} return config; });
api.interceptors.response.use(r=>r, err=>{ if(err.response?.status===401&&typeof window!=='undefined'){localStorage.clear();window.location.href='/login';} return Promise.reject(err); });
export const login=(email:string,password:string)=>api.post('/auth/login',{email,password});
export const getEmployees=()=>api.get('/employees/');
export const createEmployee=(data:any)=>api.post('/employees/',data);
export const getMyProfile=()=>api.get('/employees/me');
export const submitTimesheet=(data:any)=>api.post('/timesheets/submit',data);
export const getTimesheets=()=>api.get('/timesheets/');
export const approveTimesheet=(id:number,data:any)=>api.put('/timesheets/'+id+'/approve',data);
export const getSalaryComponents=(id:number)=>api.get('/payroll/components/'+id);
export const setSalaryComponents=(data:any)=>api.post('/payroll/components',data);
export const generatePayslip=(data:any)=>api.post('/payroll/generate',data);
export const getSalaryRecords=()=>api.get('/payroll/records');
export const downloadPayslip=(id:number)=>api.get('/payroll/slip/'+id,{responseType:'blob'});
export const getHolidays=(year?:number)=>api.get('/holidays/',{params:year?{year}:{}});
export const createHoliday=(data:any)=>api.post('/holidays/',data);
export const deleteHoliday=(id:number)=>api.delete('/holidays/'+id);
export const getDocuments=()=>api.get('/documents/');
export const uploadDocument=(fd:FormData)=>api.post('/documents/',fd,{headers:{'Content-Type':'multipart/form-data'}});
export const deleteDocument=(id:number)=>api.delete('/documents/'+id);
export const getDashboardStats=()=>api.get('/dashboard/stats');
export default api;