import{useEffect,useState}from'react';import Head from'next/head';import Layout from'../../components/common/Layout';import{downloadAppraisal,getAppraisals}from'../../services/api';import toast from'react-hot-toast';import{Download,FileText}from'lucide-react';

const label=(s:string)=>(s||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function EmployeeAppraisals(){
  const[appraisals,setAppraisals]=useState<any[]>([]);
  useEffect(()=>{getAppraisals().then(r=>setAppraisals(r.data)).catch(()=>{});},[]);
  const download=async(id:number)=>{try{const r=await downloadAppraisal(id);const url=URL.createObjectURL(new Blob([r.data],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download='appraisal.pdf';a.click();URL.revokeObjectURL(url);}catch{toast.error('Report is available after HR approval');}};
  return <><Head><title>Appraisal - CloudHub HR</title></Head><Layout><h1 className="font-bold text-2xl text-slate-800 mb-6">My Appraisals</h1>{appraisals.length===0?<div className="card text-center py-12 text-slate-400"><FileText size={32} className="mx-auto mb-2 opacity-30"/><p>No appraisals yet</p></div>:<div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{appraisals.map(a=><div key={a.id} className="card"><div className="flex justify-between items-start mb-4"><div><p className="font-semibold text-slate-800">{a.appraisal_year} {a.period}</p><span className={a.status==='approved'?'badge-approved':'badge-pending'}>{label(a.status)}</span></div><button disabled={a.status!=='approved'} onClick={()=>download(a.id)} className="p-2 hover:bg-blue-50 rounded-lg text-blue-600 disabled:text-slate-300 disabled:hover:bg-transparent" title="Download appraisal report"><Download size={18}/></button></div><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-slate-500">Rating</span><span>{a.overall_rating||'-'}</span></div><div className="flex justify-between"><span className="text-slate-500">Salary Hike</span><span>{a.salary_hike_percent?`${a.salary_hike_percent}%`:'-'}</span></div><div className="pt-2 border-t text-slate-600 line-clamp-3">{a.final_status||a.comments||'Awaiting final HR approval.'}</div></div></div>)}</div>}</Layout></>;
}
